version: '3.9'

volumes:
  games_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8888:8080"
    command: ["./Run", "migrate", "--auto-migrate"]

  db:
    image: mysql:8
    volumes:
      - games_data:/var/lib/mysql
    environment:
      MYSQL_USER: "vapor_username"
      MYSQL_PASSWORD: "1234567"
      MYSQL_DATABASE: "gamesDb"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3311:3306"
