version: '3.9'

volumes:
  games_data:

services:
  # app:
  #   image: games-api:latest
  #   build:
  #     context: .
  #   environment:
  #     <<: *shared_environment
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   user: "0"  # Uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
  #   command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  db:
    image: mysql:8
    volumes:
      - games_data:/var/lib/mysql
    environment:
      MYSQL_USER: "vapor_username"
      MYSQL_PASSWORD: "1234567"
      MYSQL_DATABASE: "gamesDb"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3311:3306"